apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: adata
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: php:8-apache
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: adata
spec:
  selector:
    app: apache
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
